[package]
name = "waga-webrtc-core"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.85"

[lib]
crate-type = ["rlib", "staticlib"]

[features]
default = ["rust-crypto"]
rust-crypto = ["str0m/rust-crypto"]
apple-crypto = ["str0m/apple-crypto"]

[dependencies]
str0m = { version = "=0.23.1", default-features = false }
